// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.fuchsia:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvzT7Oo2ipdrfzWmgwUZbXsWH92_G3ppk',
    appId: '1:182163309139:web:55122ed5b3380d71063ca6',
    messagingSenderId: '182163309139',
    projectId: 'scrum-poker-bs',
    authDomain: 'scrum-poker-bs.firebaseapp.com',
    databaseURL: 'https://scrum-poker-bs-default-rtdb.firebaseio.com',
    storageBucket: 'scrum-poker-bs.appspot.com',
    measurementId: 'G-5FWKXM8Q6N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeekHJBVw4iM5utgdnqx76JZylf7a0J9w',
    appId: '1:182163309139:android:47b44f9d294ea2ae063ca6',
    messagingSenderId: '182163309139',
    projectId: 'scrum-poker-bs',
    databaseURL: 'https://scrum-poker-bs-default-rtdb.firebaseio.com',
    storageBucket: 'scrum-poker-bs.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUSd7rU6hKQgOkuERXbBLqqZLmvo6pRzE',
    appId: '1:182163309139:ios:764caff1d8269c85063ca6',
    messagingSenderId: '182163309139',
    projectId: 'scrum-poker-bs',
    databaseURL: 'https://scrum-poker-bs-default-rtdb.firebaseio.com',
    storageBucket: 'scrum-poker-bs.appspot.com',
    iosClientId:
        '182163309139-6hfj23gscn372ms9phcc2484jg9t633c.apps.googleusercontent.com',
    iosBundleId: 'br.com.bsdev.scrumpoker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUSd7rU6hKQgOkuERXbBLqqZLmvo6pRzE',
    appId: '1:182163309139:ios:764caff1d8269c85063ca6',
    messagingSenderId: '182163309139',
    projectId: 'scrum-poker-bs',
    databaseURL: 'https://scrum-poker-bs-default-rtdb.firebaseio.com',
    storageBucket: 'scrum-poker-bs.appspot.com',
    iosClientId:
        '182163309139-6hfj23gscn372ms9phcc2484jg9t633c.apps.googleusercontent.com',
    iosBundleId: 'br.com.bsdev.scrumpoker',
  );
}
